/home/acq22ab/.conda/envs/pytorch/lib/python3.9/site-packages/torch/utils/data/dataloader.py:560: UserWarning: This DataLoader will create 8 worker processes in total. Our suggested max number of worker in current system is 1, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(
==> Using settings Namespace(dataset='h36m', keypoints='gt', actions='*', evaluate='', resume='', checkpoint='checkpoint', snapshot=5, num_layers=4, hid_dim=128, batch_size=64, epochs=40, num_workers=8, lr=0.001, lr_decay=100000, lr_gamma=0.96, max_norm=True, non_local=True, dropout=0.1, downsample=1)
==> Loading dataset...
==> Preparing data...
==> Loading 2D detections...
==> Creating model...
--- 2 hops. No transformers. No Non Local Layer
==> Total parameters: 1.06M
==> Making checkpoint dir: checkpoint/2023-08-28T16:40:21.548757
Generating 1559752 poses...
Generating 543344 poses...

Epoch: 1 | LR: 0.00100000
Traceback (most recent call last):
  File "/home/acq22ab/SemGCN/main_gcn.py", line 301, in <module>
    main(parse_args())
  File "/home/acq22ab/SemGCN/main_gcn.py", line 190, in main
    epoch_loss, lr_now, glob_step = train(train_loader, model_pos, criterion, optimizer, device, args.lr, lr_now,
  File "/home/acq22ab/SemGCN/main_gcn.py", line 237, in train
    outputs_3d = model_pos(inputs_2d)
  File "/home/acq22ab/.conda/envs/pytorch/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/acq22ab/SemGCN/models/sem_gcn12.py", line 107, in forward
    out = self.gconv_input(x)
  File "/home/acq22ab/.conda/envs/pytorch/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/acq22ab/.conda/envs/pytorch/lib/python3.9/site-packages/torch/nn/modules/container.py", line 217, in forward
    input = module(input)
  File "/home/acq22ab/.conda/envs/pytorch/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/acq22ab/SemGCN/models/sem_gcn12.py", line 23, in forward
    x = self.gconv(x).transpose(1, 2)
  File "/home/acq22ab/.conda/envs/pytorch/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/acq22ab/SemGCN/models/sem_graph_conv.py", line 399, in forward
    output = output  + output2  * self.weightage
  File "/home/acq22ab/.conda/envs/pytorch/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'SemGraphConv5' object has no attribute 'weightage'
